import numpy as np
import math
import scipy.integrate
import datetime
import threading


class Propellor(object):
    """
    This class controls a propellor for the copter class below
    Each instance of the propellor will rely on its physical parameters
    and thus will generate different thrusts or move at different speeds.

    Instance Attributes:
        diameter: The diameter of the propellor in inches [float or int]
        pitch: The pitch of the propellor in inches [float or int]
        speed: The RPM of the propellor at time t in rotation/min [float or int]
        thrust: The force generated by the propellor in Newtons [float or int]
    """
    def __init__(self, diameter, pitch):
        """docstring for the initializtion of the Propellor"""
        self.diameter = diameter
        self.pitch = pitch
        self.speed = 0 # RPM of the Propellor
        self.thrust = 0

    def setSpeed(self, speed):
        """docstring for setting the speed"""
        self.speed = speed
        ### The link below was used for thrust calculations, this is a
        ### simplified form, which will undershoot dynamic thrust and
        ### overshoot static thrust by ~ 15%-30%
        ### http://www.electricrcaircraftguy.com/2013/09/propeller-static-dynamic-thrust-equation.html
        self.thrust = 4.392e-8 * self.speed * math.pow(self.diameter,3.5)
        self.thrust = self.thrust / math.sqrt(self.pitch)
        self.thrust = self.thrust * (4.23e-4 * self.speed * self.pitch)


class Copter(object):
    """docstring for Copter."""
    def __init__(self, arg):
        self.arg = arg


class QuadCopter(Copter):
    """docstring for QuadCopter."""
    def __init__(self, arg):
        super(QuadCopter, self).__init__()
        self.arg = arg
